accelerator: null
accumulate_grad_batches: null
amp_backend: null
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_size: 500
benchmark: null
check_val_every_n_epoch: 1
data_path:
- !!python/object/apply:pathlib.PosixPath
  - data
  - training_datasets
  - to_LSZH_16_100_west.pkl
- !!python/object/apply:pathlib.PosixPath
  - data
  - training_datasets
  - ga_LSZH_14_100.pkl
default_root_dir: null
detect_anomaly: false
devices: null
dilation_base: 2
dropout: 0.0
early_stop: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
encoding_dim: 10
fast_dev_run: false
features:
- track
- groundspeed
- altitude
- timedelta
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: 0.5
h_dims:
- 64
- 64
- 64
- 64
- 64
inference_mode: true
info_features: []
info_index: null
ipus: null
kernel_size: 16
kld_coef: 40.0
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
llv_coef: 1.0
log_every_n_steps: 50
logger: true
lr: 0.001
lr_gamma: 0.5
lr_step_size: 200
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_components: 2
n_samples: 20000
network_name: tcvae_pairs_disent
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
post_coef: 0.0
precision: 32
prior: factorized_vampprior
prior_coef: 0.0
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
sampling_factor: 10
scale: 1.0
strategy: null
sync_batchnorm: false
tc_coef: 40.0
test_batch_size: null
tpu_cores: null
track_grad_norm: -1
train_ratio: 0.8
val_check_interval: null
val_ratio: 0.2
